# Generated by Django 3.1.7 on 2021-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='controller',
            field=models.CharField(max_length=200),
        ),
    ]
