# Generated by Django 3.1.7 on 2021-04-24 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210424_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolepermissions',
            old_name='Permission_id',
            new_name='permission_id',
        ),
    ]
