# Generated by Django 3.2 on 2021-06-08 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_permission_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_deleted',
        ),
    ]
