# Generated by Django 3.1.7 on 2021-04-20 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210419_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='controller',
            new_name='permission',
        ),
    ]
