# Generated by Django 3.1.7 on 2021-04-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210426_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role_id',
            field=models.IntegerField(),
        ),
    ]
