# Generated by Django 3.2 on 2021-05-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210518_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
