# Generated by Django 3.2 on 2021-05-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_permission_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
    ]
