# Generated by Django 3.2 on 2021-05-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210531_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='deleted_at',
        ),
    ]
