# Generated by Django 3.2 on 2021-05-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_permission_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
