# Generated by Django 3.2 on 2021-06-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_permission_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='permission',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
