# Generated by Django 3.2 on 2021-06-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20210602_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='deleted',
        ),
    ]
