# Generated by Django 3.2 on 2021-06-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_permission_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
