# Generated by Django 3.2 on 2021-06-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_permission_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='deleted',
        ),
        migrations.AddField(
            model_name='permission',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
    ]
