# Generated by Django 3.2 on 2021-06-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20210604_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
