# Generated by Django 3.2 on 2021-06-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_permission_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='deleted_at',
        ),
    ]
