# Generated by Django 3.2 on 2021-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_permission_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='permission',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
